name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        serverless-version:
          - "1.60"
          - "1.59"
          - "1.58"
          - "1.57"
          - "1.56"
          - "1.55"
          - "1.54"
          - "1.53"
          - "1.52"
          - "1.51"
          - "1.50"

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm i --save-dev serverless@${{ matrix.serverless-version }} serverless-glob-merge-yaml
      - run: npm test
